spring:
  application: scb-openapi-demo
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
#    url: jdbc:mysql://localhost:3306/cashless-demo
#    username: cashless
#    password: N0sSl#123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://cashless-mysql.mysql.database.azure.com:3306/cashless?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cashless@cashless-mysql
    password: "N0sSl#123"

logging:
  config: classpath:config/log4j2.xml